---
title: "Homework 5 Vectors"
author: "AWhitten"
date: "3/31/2021"
output: html_document
---


# Question One
## Assign x, a, and b.
```{r}
x <- 1.1
a <- 2.2
b <- 3.3
```
## Part a
```{r}
z <- x^a^b
print(z)
```
## Part b
```{r}
z <- (x^a)^b
print(z)
```
## Part c
```{r}
z<- 3*(x^3) + 2*(x^2) + 1
print(z)
```


# Question Two: rep() and seq() to create vectors
## Part a
```{r}
vec_one <- c(seq(from=1, to=8),seq(from=7, to=1))
print(z)
```
## Part b
```{r}
vec_two <- c(1,rep(2,2),rep(3,3),rep(4,4),rep(5,5))
print(vec_two)
```
## Part c
```{r}
vec_three <- c(5,rep(4,2),rep(3,3),rep(2,4),rep(1,5))
print(vec_three)
```

# Question Three: Create polar coodinates
```{r}
vec_four <- runif(2) # generate two random numbers
print(vec_four)

r <-sqrt(vec_four[1]^2 +vec_four[2]^2) # calculate r
theta <- atan(vec_four[1]/vec_four[2]) # calculate theta
polar_cor <- c(r,theta) # create assignment 
print(polar_cor)
```

# Question Four: Update line of animals
```{r}
queue <- c("sheep", "fox", "owl", "ant")
queue <-c(queue, "serpent") # add serpent
print(queue)

queue<-queue[-c(1)] #remove sheep
print(queue)

queue<-c("donkey",queue) # add donkey to font of line
print(queue)

queue<-queue[-5] # serpent leaves
print(queue)

queue<-queue[-3] # owl leaves
print(queue)

queue<- c(queue[1:2],"aphid", "ant") # aphid enters before ant
print(queue)

which(queue =="aphid") # determine aphid position
```
# Question Five: Create Vectors
## Vector of integers 1-100 not divisible by 2, 3, or 7
```{r}
# not divisible by 2
z <- 1:100
z <- z[which(z%%2 != FALSE)]
print(z)

# not divisible by 3
z <- z[which(z%%3 != FALSE)]
print(z)

# not divisible by 7
z <- z[which(z%%7 != FALSE)]

# final list
print(z)
```

